#!/bin/bash
# Script name
scriptversion="1.0.0"
scriptname="madsonic"
# randomessence
#
# wget -qO ~/madsonic.sh http://git.io/0510Pw && bash ~/madsonic.sh
#
############################
## Version History Starts ##
############################
#
# How do I customise this updater? 
# 1: scriptversion="0.0.0" replace "0.0.0" with your script version. This will be shown to the user at the current version.
# 2: scriptname="somescript" replace "somescript" with your script name. this will be shown to the user when they first run the script.
# 3: Search and replace all instances of "somescript", 29 including this one, with the name of your script, do not include the .sh aside from doing step 2.
# 4: Then replace ALL "https://raw.github.com/feralhosting" with the URL to the RAW script URL.
# 5: Insert you script in the "Script goes here" labelled section 
#
# This updater deals with updating two files at the same time, the  "~/somescript.sh" and the "~/bin/somescript" . You can remove one part of the updater, if you wish, to focus on a single file instance.
#
# v1.0.0 splitting the script to treat Madsonic and Subsonic as separate installs.
#
############################
### Version History Ends ###
############################
#
# See version.txt
#
############################
###### Variable Start ######
############################
#
# Sets a random port between 6000-50000 for http
http=$(shuf -i 6000-50000 -n 1)
# Defines https as + 1 from http
https=$(expr 1 + $http)
# Defines the memory memory variable
initmemory="2048"
maxmemory="3072"
# Gets the Java version from the last time this scrip installed Java
installedjavaversion=$(cat ~/programs/javaversion 2> /dev/null)
# Java URL
javaupdatev="http://javadl.sun.com/webapps/download/AutoDL?BundleId=81812"
# Some variable links for madsonic
madsonicfv="https://bitbucket.org/feralhosting/feralfiles/downloads/5.0.3780-standalone.zip"
madsonicfvs="5.0.3780-standalone.zip"
# Madsonic custom ffmpeg with Audioffmpeg
mffmpegfvc="https://bitbucket.org/feralhosting/feralfiles/downloads/ffmpeg.31.10.2013.zip"
mffmpegfvcs="ffmpeg.31.10.2013.zip"
#
############################
####### Variable End #######
############################
#
############################
#### Self Updater Start ####
############################
#
mkdir -p $HOME/bin
#
if [[ ! -f "$HOME/madsonic.sh" ]]
then
    wget -qO $HOME/madsonic.sh https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
fi
if [[ ! -f "$HOME/bin/madsonic" ]]
then
    wget -qO $HOME/bin/madsonic https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
fi
#
wget -qO $HOME/000madsonic.sh https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
#
if ! diff -q "$HOME/000madsonic.sh" "$HOME/madsonic.sh" > /dev/null 2>&1
then
    echo '#!/bin/bash
    wget -qO $HOME/madsonic.sh https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
    wget -qO $HOME/bin/madsonic https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
    bash $HOME/madsonic.sh
    exit 1' > $HOME/111madsonic.sh
    bash $HOME/111madsonic.sh
    exit 1
fi
if ! diff -q "$HOME/000madsonic.sh" "$HOME/bin/madsonic" > /dev/null 2>&1
then
    echo '#!/bin/bash
    wget -qO $HOME/madsonic.sh https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
    wget -qO $HOME/bin/madsonic https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh
    bash $HOME/madsonic.sh
    exit 1' > $HOME/222madsonic.sh
    bash $HOME/222madsonic.sh
    exit 1
fi
#
echo
echo -e "Hello $(whoami), you have the latest version of the" "\033[36m""$scriptname""\e[0m" "script. This script version is:" "\033[31m""$scriptversion""\e[0m"
echo
#
rm -f $HOME/000madsonic.sh $HOME/111madsonic.sh $HOME/222madsonic.sh
chmod -f 700 $HOME/bin/madsonic
#
############################
##### Self Updater End #####
############################
#
#############################
#### madsonicrsk starts  ####
#############################
#
echo -e "#!/bin/bash
#
httpport=\$(sed -n -e 's/MADSONIC_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)
httpsport=\$(sed -n -e 's/MADSONIC_HTTPS_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)
#
# v 1.2.0  Kill Start Restart Script generated by the Madsonic installer script
#
echo
echo -e \"\\\033[33m1:\\\e[0m This is the process PID:\\\033[32m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m used the last time \\\033[36m~/private/madsonic/madsonic.sh\\\e[0m was started.\"
echo
echo -e \"\\\033[33m2:\\\e[0m These are the URLs and ports Madsonic is configured to use:\"
echo
echo -e \"\\\033[31mHTTP\\\e[0m last accessible at \\\033[31mhttp://\$(hostname)\\\e[0m:\\\033[33m\$httpport\\\e[0m\"
echo -e \"\\\033[32mHTTPS\\\e[0m last accessible at \\\033[32mhttps://\$(hostname)\\\e[0m:\\\033[33m\$httpsport\\\e[0m\"
echo
echo -e \"\\\033[33m3:\\\e[0m Running instances checks:\"
echo
echo -e \"Checking to see, specifically, if the \\\033[32m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m is running\"
echo -e \"\\\033[32m\"
if [[ -z \"\$(ps -p \$(cat ~/private/madsonic.sh.PID/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null)\" ]]
then
    echo -e \"Nothing to show.\"
    echo -e \"\\\e[0m\"
else
    ps -p \$(cat ~/private/madsonic.sh.PID/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null
    echo -e \"\\\e[0m\"
fi
if [[ \"\$(ps -U \$(whoami) | grep -c java)\" -gt \"1\" ]]
then
    echo -e \"There are currently \\\033[31m\$(ps -U \$(whoami) | grep -c java 2> /dev/null)\\\e[0m running Java processes.\"
    echo -e \"\\\033[31mWarning:\\\e[0m \\\033[32mMadsonic might not load or be unpredicatable with multiple instances running.\\\e[0m\"
    echo -e \"\\\033[33mIf there are multiple Madsonic processes please use the killall by using option [a] then use the restart option.\\\e[0m\"
    echo -e \"\\\033[31m\"
    ps -U \$(whoami) | grep java
    echo -e \"\\\e[0m\"
fi
echo -e \"\\\033[33m4:\\\e[0m Options for killing and restarting Madsonic:\"
echo
echo -e \"\\\033[36mKill PID only\\\e[0m \\\033[31m[y]\\\e[0m \\\033[36mKillall java processes\\\e[0m \\\033[31m[a]\\\e[0m \\\033[36mSkip to restart (where you can quit the script)\\\e[0m \\\033[31m[r]\\\e[0m\"
echo
read -ep \"Please press one of these options [y] or [a] or [r] and press enter: \"  confirm
echo
if [[ \$confirm =~ ^[Yy]\$ ]]
then
    kill -9 \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) 2> /dev/null
    echo -e \"The process PID:\\\033[31m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m that was started by the installer or custom scripts has been killed.\"
    echo
    echo -e \"Checking to see if the PID:\\\033[32m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m is running:\\\e[0m\"
    echo -e \"\\\033[32m\"
    if [[ -z \"\$(ps -p \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null)\" ]]
    then
        echo -e \"Nothing to show, job done.\"
        echo -e \"\\\e[0m\"
    else
        ps -p \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null
        echo -e \"\\\e[0m\"
    fi
elif [[ \$confirm =~ ^[Aa]\$ ]]
then
    killall -9 -u \$(whoami) java 2> /dev/null
    echo -e \"\\\033[31mAll java processes have been killed\\\e[0m\"
    echo
    echo -e \"\\\033[33mChecking for open java processes:\\\e[0m\"
    echo -e \"\\\033[32m\"
    if [[ -z \"\$(ps -U \$(whoami) | grep java 2> /dev/null)\" ]]
    then
        echo -e \"Nothing to show, job done.\"
        echo -e \"\\\e[0m\"
    else
        ps -U \$(whoami) | grep java
        echo -e \"\\\e[0m\"
    fi
else
    echo -e \"Skipping to restart or quit\"
    echo
fi
if [[ -f ~/private/madsonic/madsonic.sh ]]
then
    read -ep \"Would you like to restart Madsonic? [r] reload the kill features? [l] or quit the script? [q]: \"  confirm
    echo
    if [[ \$confirm =~ ^[Rr]\$ ]]
    then
        if [[ -z \"\$(ps -p \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null)\" ]]
        then
            bash ~/private/madsonic/madsonic.sh
            echo -e \"Started Madsonic at PID:\\\033[31m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m\"
            echo
            echo -e \"\\\033[31mHTTP\\\e[0m Accessible at \\\033[31mhttp://\$(hostname)\\\e[0m:\\\033[33m\$httpport\\\e[0m\"
            echo -e \"\\\033[32mHTTPS\\\e[0m Accessible at \\\033[32mhttps://\$(hostname)\\\e[0m:\\\033[33m\$httpsport\\\e[0m\"
            echo -e \"\\\033[32m\"
            if [[ -z \"\$(ps -p \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null)\" ]]
            then
                echo -e \"Nothing to show, job done.\"
                echo -e \"\\\e[0m\"
            else
                ps -p \$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null) --no-headers 2> /dev/null
                echo -e \"\\\e[0m\"
            fi
            exit 1
        else
            echo -e \"Madsonic with the PID:\\\033[32m\$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)\\\e[0m is already running. Kill it first then restart\"
            echo
            read -ep \"Would you like to restart the RSK script? [y] reload it? [q] or quit the script?: \"  confirmrsk
            echo
            if [[ \$confirmrsk =~ ^[Yy]\$ ]]
            then
                bash ~/bin/madsonicrsk
            fi
            exit 1
        fi
    elif [[ \$confirm =~ ^[Ll]\$ ]]
    then
        echo -e \"\\\033[31mReloading madsonicrsk to access kill features.\\\e[0m\"
        echo
        bash ~/bin/madsonicrsk
    else
        echo This script has done its job and will now exit.
        echo
        exit 1
    fi
else
    echo
    echo -e \"The \\\033[31m~/private/madsonic/madsonic.sh\\\e[0m does not exist.\"
    echo -e \"please run the \\\033[31m~/madsonic.sh\\\e[0m to install and configure madsonic\"
    exit 1
fi" > ~/bin/madsonicrsk
#
#############################
##### madsonicrsk ends  #####
#############################
#
#############################
#### madsonicron starts  ####
#############################
#
echo '#!/bin/bash
echo "$(date +"%H:%M on the %d.%m.%y")" >> madsonicrun.log
if [[ -z "$(ps -p $(cat ~/private/madsonic/madsonic.sh.PID) --no-headers)" ]]
then
    bash ~/private/madsonic/madsonic.sh
else
    exit 1
fi' > ~/bin/madsonicron
#
#############################
##### madsonicron ends  #####
#############################
#
# Make the ~/bin/madsonicrsk and ~/bin/madsonicron files we created executable
chmod -f 700 ~/bin/madsonicrsk
chmod -f 700 ~/bin/madsonicron
#
echo -e "The" "\033[36m""~/bin/madsonicrsk""\e[0m" "has been updated."
echo
read -ep "The scripts have been updated, do you wish to continue [y] or exit now [q] : " updatestatus
echo
if [[ $updatestatus =~ ^[Yy]$ ]]
then
#
############################
####### Script Start #######
############################
#
    echo -e "\033[31m""User Notice:""\e[0m" "\033[33m""This is a user supported script. Please don't expect or ask staff to support this directly.\nTo get support you can jump on IRC and ask other users for help.\nAll critical bugs should be reported and bug fixes or improvements are welcomed and encouraged.""\e[0m"
    echo
    # A user notice regarding what support is available for this script and how to contribute.
    sleep 2
    ###### Install Java 1.7 Start
    if [[ "$installedjavaversion" != "$javaversion" ]]
    then
        echo "Please wait a moment while java is installed"
        rm -rf ~/private/java
        wget -qO ~/java.tar.gz $javaupdatev
        tar xf ~/java.tar.gz
        cp -rf ~/jre$jvdecimal/. ~/programs
        rm -f ~/java.tar.gz
        rm -rf ~/jre$jvdecimal
        if [[ ! "$(grep -o 'PATH=~/programs/bin:$PATH' ~/.bashrc)" ]]
        then
            echo 'export PATH=~/programs/bin:$PATH' >> ~/.bashrc
        fi
        echo -n "$javaversion" > ~/programs/javaversion
        # we create a custom Java version file for comparison so the installer only runs once
        echo -e "\033[31m""Important:""\e[0m" "Java" "\033[32m""$javaversion""\e[0m" "has been installed to" "\033[36m""~/private/java""\e[0m"
        echo
        echo -e "This Script needs to exit for the Java changes to take effect. Please restart the Script using this command:"
        echo
        echo 'bash ~/madsonic.4.8.sh'
        echo
        bash
        exit 1
    fi
    ### Install Java 1.7 end
    if [[ ! -d ~/private/madsonic/ ]]
    then
        echo -e "Congratulations," "\033[31m""Java is installed""\e[0m"". Continuing with the installation."
        sleep 1
        echo
        # An echo telling the user that Java is already installed.
        echo -e "Path" "\033[36m""~/private/madsonic/""\e[0m" "created. Moving to next step."
        mkdir -p ~/sonictmp
        mkdir -p ~/private/madsonic/transcode
        mkdir -p ~/private/madsonic/playlists
        mkdir -p ~/private/madsonic/Incoming
        mkdir -p ~/private/madsonic/Podcast
        mkdir -p ~/private/madsonic/playlist-import
        mkdir -p ~/private/madsonic/playlist-export
        echo -n "$madsonicfvs" > ~/private/madsonic/.version
        echo
        # Creates some directories we need for configuring the start-up script
        echo -e "\033[32m""$madsonicfvs""\e[0m" "Is downloading now."
        wget -qO ~/sonictmp/madsonic.zip $madsonicfv
        echo -e "\033[36m""$madsonicfvs""\e[0m" "Has been downloaded and renamed to" "\033[36m""madsonic.zip\e[0m"
        # Gets the latest version of madsonic from sourceforge. Currently at 4.8
        #
        echo -e "\033[36m""madsonic.zip""\e[0m" "Is unpacking now."
        unzip -qo ~/sonictmp/madsonic.zip -d ~/private/madsonic
        echo -e "\033[36m""madsonic.zip""\e[0m" "Has been unpacked to" "\033[36m""~/private/madsonic/\e[0m"
        # Unpack this this version from its tar.gz archive to the ~/private/madsonic/ directory
        sleep 1
        echo
        # tidy up
        #
        echo -e "\033[32m""$mffmpegfvcs""\e[0m" "Is downloading now."
        wget -qO ~/sonictmp/ffmpeg.zip $mffmpegfvc
        echo -e "\033[36m""$mffmpegfvcs""\e[0m" "Has been downloaded and renamed to" "\033[36m""ffmpeg.tar.gz\e[0m"
        # Downloads a perma hosted version of ffmpeg static and renames it to ffmpeg.tar.gz. Dated at 04/24/2013
        #
        echo -e "\033[36m""$mffmpegfvcs""\e[0m" "Is being unpacked now."
        unzip -qo ~/sonictmp/ffmpeg.zip -d ~/private/madsonic/transcode/
        chmod -f 700 ~/private/madsonic/transcode/Audioffmpeg ~/private/madsonic/transcode/ffmpeg
        # cp -f ~/private/madsonic/transcode/ffmpeg ~/private/madsonic/transcode/Audioffmpeg 2> /dev/null
        echo -e "\033[36m""$mffmpegfvcs""\e[0m" "Has been unpacked to" "\033[36m~/private/madsonic/transcode/\e[0m"
        # Unpacks this static ffmpeg binary from its tar.gz archive to ~/private/madsonic/transcode/
        rm -rf ~/sonictmp
        sleep 1
        echo
        # tidy up
        #
        echo -e "\033[32m""Copying over a local version of lame.""\e[0m"
        # cp -f /usr/local/bin/lame ~/private/madsonic/transcode/ 2> /dev/null
        chmod -f 700 ~/private/madsonic/transcode/lame
        echo -e "Lame copied to" "\033[36m""~/private/madsonic/transcode/\e[0m"
        sleep 1
        echo
        # copies over the local version of lame to ~/private/madsonic/transcode/
        #
        echo -e "\033[32m""Copying over a local version of Flac.""\e[0m"
        cp -f /usr/bin/flac ~/private/madsonic/transcode/ 2> /dev/null
        chmod -f 700 ~/private/madsonic/transcode/flac
        echo -e "Flac copied to" "\033[36m""~/private/madsonic/transcode/""\e[0m"
        sleep 1
        echo
        # copies over the local version of Flac to ~/private/madsonic/transcode/
        #
        echo -e "\033[31m""Configuring the start-up script.""\e[0m"
        echo -e "\033[35m""User input is required for this next step:""\e[0m"
        echo -e "\033[33m""Note on user input:""\e[0m" "It is OK to use a relative path like:" "\033[33m""~/private/rtorrent/data""\e[0m"
        #
        sed -i 's|MADSONIC_HOME=/var/madsonic|MADSONIC_HOME=~/private/madsonic|g' ~/private/madsonic/madsonic.sh
        sed -i "s/MADSONIC_PORT=4040/MADSONIC_PORT=$http/g" ~/private/madsonic/madsonic.sh
        sed -i "s/MADSONIC_HTTPS_PORT=0/MADSONIC_HTTPS_PORT=$https/g" ~/private/madsonic/madsonic.sh
        sed -i "s/MADSONIC_INIT_MEMORY=256/MADSONIC_INIT_MEMORY=$initmemory/g" ~/private/madsonic/madsonic.sh
        sed -i "s/MADSONIC_MAX_MEMORY=350/MADSONIC_MAX_MEMORY=$maxmemory/g" ~/private/madsonic/madsonic.sh
        sed -i '0,/MADSONIC_PIDFILE=/s|MADSONIC_PIDFILE=|MADSONIC_PIDFILE=~/private/madsonic/madsonic.sh.PID|g' ~/private/madsonic/madsonic.sh
        # Edit the mains settings.
        #
        read -ep "Enter the path to your media or leave blank and press enter to skip: " path
        sed -i "s|MADSONIC_DEFAULT_MUSIC_FOLDER=/var/media|MADSONIC_DEFAULT_MUSIC_FOLDER=$path|g" ~/private/madsonic/madsonic.sh
        sed -i 's|MADSONIC_DEFAULT_UPLOAD_FOLDER=/var/media/Incoming|MADSONIC_DEFAULT_UPLOAD_FOLDER=~/private/madsonic/Incoming|g' ~/private/madsonic/madsonic.sh
        sed -i 's|MADSONIC_DEFAULT_PODCAST_FOLDER=/var/media/Podcast|MADSONIC_DEFAULT_PODCAST_FOLDER=~/private/madsonic/Podcast|g' ~/private/madsonic/madsonic.sh
        sed -i 's|MADSONIC_DEFAULT_PLAYLIST_IMPORT_FOLDER=/var/media/playlist-import|MADSONIC_DEFAULT_PLAYLIST_IMPORT_FOLDER=~/private/madsonic/playlist-import|g' ~/private/madsonic/madsonic.sh
        sed -i 's|MADSONIC_DEFAULT_PLAYLIST_EXPORT_FOLDER=/var/media/playlist-export|MADSONIC_DEFAULT_PLAYLIST_EXPORT_FOLDER=~/private/madsonic/playlist-export|g' ~/private/madsonic/madsonic.sh
        # Edit the paths
        #
        sed -i 's/quiet=0/quiet=1/g' ~/private/madsonic/madsonic.sh
        # Set the process to be quiet
        #
        sed -i "22 i export LC_ALL=en_GB.UTF-8\n" ~/private/madsonic/madsonic.sh
        sed -i '22 i export LANG=en_GB.UTF-8' ~/private/madsonic/madsonic.sh
        sed -i '22 i export LANGUAGE=en_GB.UTF-8' ~/private/madsonic/madsonic.sh
        # Add some locale settings in case they are not set already to work with UTF characters
        #
        echo
        echo -e "\033[31m""Start-up script successfully configured.""\e[0m"
        #
        #
        echo "Executing the start-up script now."
        #
        #
        bash ~/private/madsonic/madsonic.sh
        # starts madsonic using the pre configured madsonic.sh
        #
        echo -e "A restart/start/kill script has been created at:" "\033[35m""~/bin/madsonicrsk""\e[0m"
        #
        echo -e "\033[32m""Madsonic is now started, use the links below to access it. Don't forget to set path to FULL path to you music folder in the gui.""\e[0m"
        sleep 1
        # Job done echo
        #
        echo
        echo -e "\033[31m""HTTP""\e[0m" "is accessible at" "\033[31m""http://$(hostname)""\e[0m"":""\033[33m""$(sed -n 's/MADSONIC_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)""\e[0m"
        echo -e "HTTPS uses a custom but invalid []#'.org cert and not one from Feral. It is safe to accept."
        echo -e "\033[32m""HTTPS""\e[0m" "is accessible at" "\033[32m""https://$(hostname)""\e[0m"":""\033[33m""$(sed -n 's/MADSONIC_HTTPS_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)""\e[0m"
        echo
        echo -e "Madsonic started at PID:" "\033[31m""$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)""\e[0m"
        echo
        # urls and warnings are printed for the user to select and read.
        bash
        exit 1
    else
        echo -e "\033[31m""Madsonic appears to already be installed.""\e[0m" "Please kill the PID:" "\033[33m""$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)""\e[0m" "if it is running and delete the" "\033[36m""~/private/madsonic directory""\e[0m"
        echo
        read -ep "Would you like me to kill Java (all Java processes) and remove the directories for you? [y] or update your installation [u] quit now [q]: "  confirm
        if [[ $confirm =~ ^[Yy]$ ]]
        then
            echo
            echo "Killing all Java processes."
            killall -9 -u $(whoami) java 2> /dev/null
            echo -e "\033[31m" "Done""\e[0m"
            sleep 1
            echo "Removing ~/private/madsonic"
            rm -rf ~/private/madsonic
            echo -e "\033[31m" "Done""\e[0m"
            sleep 1
            echo "Removing RSK scripts if present."
            rm -f ~/madsonicstart.sh
            rm -f ~/madsonicrestart.sh
            rm -f ~/madsonickill.sh
            rm -f ~/madsonicrsk.sh
            rm -f ~/bin/madsonicrsk
            rm -f ~/bin/madsonicron
            # legacy removals
            echo -e "\033[31m" "Done""\e[0m"
            sleep 1
            echo "Finalising removal."
            rm -rf ~/private/madsonic
            echo -e "\033[31m" "Done and Done""\e[0m"
            echo
            sleep 1
            read -ep "Would you like you relaunch the installer [y] or quit [q]: "  confirm
            if [[ $confirm =~ ^[Yy]$ ]]
            then
                echo
                echo -e "\033[32m" "Relaunching the installer.""\e[0m"
                if [[ -f ~/madsonic.4.8.sh ]] 
                then
                    bash ~/madsonic.4.8.sh
                else
                    wget -qO ~/madsonic.sh https://raw.github.com/feralhosting/feralfilehosting/master/Feral%20Wiki/Software/Subsonic%204.8/scripts/madsonic/madsonic.sh/feralfilehosting/master/
                    bash ~/madsonic.4.8.sh
                fi
            else
                exit 1
            fi
        elif [[ $confirm =~ ^[Uu]$ ]]
        then
            echo -e "Madsonic is being updated. This will only take a moment."
            echo
            killall -9 -u $(whoami) java 2> /dev/null
            mkdir -p ~/sonictmp
            wget -qO ~/madsonic.zip $madsonicfv
            unzip -qo ~/madsonic.zip -d ~/sonictmp
            rm -f ~/sonictmp/madsonic.sh
            cp -rf ~/sonictmp/. ~/private/madsonic/
            wget -qO ~/madffmpeg.zip $mffmpegfvc
            unzip -qo ~/madffmpeg.zip -d ~/private/madsonic/transcode
            chmod -f 700 ~/private/madsonic/transcode/Audioffmpeg ~/private/madsonic/transcode/ffmpeg
            echo -n "$madsonicfvs" > ~/private/madsonic/.version
            rm -rf ~/madsonic.zip ~/madffmpeg.zip ~/sonictmp
            bash ~/private/madsonic/madsonic.sh
            echo -e "A restart/start/kill script has been created at:" "\033[35m""~/bin/madsonicrsk""\e[0m"
            echo -e "\033[32m""Madsonic is now started, use the links below to access it. Don't forget to set path to FULL path to you music folder in the gui.""\e[0m"
            sleep 1
            echo
            echo -e "\033[31m""HTTP""\e[0m" "is accessible at" "\033[31m""http://$(hostname)""\e[0m"":""\033[33m""$(sed -n -e 's/MADSONIC_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)""\e[0m"
            echo -e "HTTPS uses a custom but invalid subsonic.org cert and not one from Feral. It is safe to accept."
            echo -e "\033[32m""HTTPS""\e[0m" "is accessible at" "\033[32m""https://$(hostname)""\e[0m"":""\033[33m""$(sed -n -e 's/MADSONIC_HTTPS_PORT=\([0-9]\+\)/\1/p' ~/private/madsonic/madsonic.sh 2> /dev/null)""\e[0m"
            echo
            echo -e "Madsonic started at PID:" "\033[31m""$(cat ~/private/madsonic/madsonic.sh.PID 2> /dev/null)""\e[0m"
            echo
            bash
            exit 1
        else
            echo
            exit 1
        fi
    fi
############################
####### Script Ends  #######
############################
#
else
    echo -e "You chose to exit after updating the scripts."
    exit 1
    cd && bash
fi